// Blog.js
import { useParams } from "react-router-dom";

const Blog = () => {
  const { id } = useParams();
  const blogContent = {
    1: "Taking care of oily skin involves a consistent skincare routine that focuses on cleansing, exfoliating, moisturizing, and controlling shine. Start by cleansing your face twice daily with a gentle, oil-free cleanser to remove excess oil and prevent clogged pores. Exfoliate once or twice a week using a mild scrub or chemical exfoliant to eliminate dead skin cells and keep pores clear. Even oily skin needs hydration, so use a lightweight, oil-free moisturizer to balance moisture without causing excess shine. Opt for oil-free makeup and mattifying products to control shine, and use blotting papers throughout the day to absorb oil without disrupting your makeup. Incorporate clay masks weekly to deep clean and tighten pores, and avoid touching your face to prevent transferring oil and bacteria. Maintaining a balanced diet, drinking water, and consulting a dermatologist for persistent issues can also support healthy, oil-free skin.",
    2: "A great skincare routine for oily skin starts with a gentle, oil-free foaming or gel-based cleanser used twice daily to remove excess oil and prevent clogged pores. Follow up with an optional alcohol-free toner containing ingredients like witch hazel or niacinamide to balance oil production and tighten pores. Exfoliate 2-3 times a week with a mild exfoliator containing salicylic acid or glycolic acid to remove dead skin cells and prevent breakouts. Apply a lightweight, oil-free moisturizer morning and night to maintain hydration without adding shine, and use a serum with niacinamide or hyaluronic acid to control oil and target acne. Never skip sunscreen with SPF 30 or higher in the morning, opting for a matte or oil-free formula. Once a week, treat your skin with a clay mask to absorb excess oil and deep clean pores. Additionally, avoid over-washing your face and use blotting papers during the day to absorb oil without disturbing your makeup. This balanced routine helps manage oil, prevent acne, and maintain healthy, clear skin.",
    3: "For sensitive skin, a gentle and soothing skincare routine is essential to avoid irritation and maintain balance. Start with a mild, fragrance-free cleanser that is specifically formulated for sensitive skin, cleansing your face twice a day to remove dirt and excess oils without stripping the skin's natural moisture. Follow with a calming toner that contains hydrating ingredients like aloe vera or chamomile, avoiding alcohol-based toners that can irritate. Exfoliate gently once a week using a chemical exfoliant with mild ingredients like lactic acid, as physical scrubs can be too abrasive. Apply a fragrance-free, hydrating moisturizer rich in ceramides or hyaluronic acid to lock in moisture and strengthen the skin's barrier. For sun protection, choose a mineral sunscreen with zinc oxide or titanium dioxide that is formulated for sensitive skin to protect from UV rays without causing irritation. You may also use soothing face masks with calming ingredients like oatmeal or honey once a week. Throughout the day, avoid touching your face or using harsh products, and always patch test new products to prevent unwanted reactions. This routine helps maintain hydration, calm inflammation, and protect sensitive skin while keeping it healthy and nourished.",
    4: "A nighttime skincare routine is essential for rejuvenating and repairing the skin while you sleep. At night, the skin enters recovery mode, working to repair damage from exposure to environmental stressors like UV rays and pollution. A typical nighttime routine begins with a gentle cleanser to remove makeup, dirt, and impurities, followed by a toner to balance the skin's pH. Using targeted treatments, like serums with ingredients such as retinol, hyaluronic acid, or antioxidants, helps address specific concerns such as fine lines, dryness, or dullness. Locking in moisture with a rich night cream or moisturizer supports hydration and plumpness, while an eye cream can reduce puffiness and dark circles. With consistency, a well-tailored nighttime skincare routine can promote clearer, healthier, and more radiant skin.",
    5: "A daytime skincare routine is designed to protect and hydrate the skin throughout the day, helping it to combat environmental stressors like UV rays, pollution, and dryness. It usually begins with a gentle cleanser to start with a fresh, clean base. Following cleansing, a toner can balance the skin's pH and prep it for the next steps. Applying a serum, like one with vitamin C, provides antioxidant protection and a brightening effect. Moisturizing is essential for keeping the skin hydrated and resilient, even if you have oily skin; a lightweight moisturizer often works well for daytime. The final and most crucial step is applying a broad-spectrum SPF to protect the skin from harmful UV rays, which can cause premature aging, pigmentation, and sun damage. Together, these steps work to keep the skin hydrated, protected, and radiant throughout the day.",
    6: "Sunscreen is a critical yet often overlooked component of a comprehensive skincare routine. Its primary purpose is to shield the skin from the sun's harmful ultraviolet (UV) rays, which are known to cause skin damage, premature aging, and an increased risk of skin cancer. There are two main types of UV rays: UVA rays, which penetrate deeply and cause wrinkles and age spots, and UVB rays, which lead to sunburn. Sunscreens with broad-spectrum protection guard against both, creating a barrier that minimizes UV damage. Daily application of sunscreen, regardless of the weather or season, is essential because UV rays can penetrate clouds and even glass windows. Beyond protection, using sunscreen can help maintain an even skin tone by preventing hyperpigmentation and dark spots, which often arise from sun exposure. In addition to helping the skin retain its youthful appearance, a good sunscreen also complements other skincare products, enhancing the effectiveness of anti-aging and brightening ingredients by protecting against further damage. Whether for health or cosmetic reasons, sunscreen is an irreplaceable step in ensuring long-term skin health and resilience.",
  };

  return (
    <div>
      <h1>Blog Post #{id}</h1>
      <p>{blogContent[id]}</p>
    </div>
  );
};

export default Blog;
